# Generated by Django 6.0.7 on 2026-07-14 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('role', models.CharField(choices=[('Manager', 'Manager'), ('Reception', 'Reception'), ('Trainer', 'Trainer')], default='Reception', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
