# Generated by Django 6.0.7 on 2026-07-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='member',
            name='fee_status',
        ),
        migrations.RemoveField(
            model_name='member',
            name='next_due_date',
        ),
        migrations.RemoveField(
            model_name='member',
            name='payment_mode',
        ),
        migrations.AddField(
            model_name='member',
            name='address',
            field=models.TextField(default='N/A'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='member',
            name='member_id',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='member',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10),
        ),
        migrations.AddField(
            model_name='member',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='member',
            name='age',
            field=models.PositiveIntegerField(),
        ),
    ]
