# Generated by Django 6.0.7 on 2026-07-11 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_rename_name_member_full_name_remove_member_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='plan',
            new_name='membership',
        ),
        migrations.RemoveField(
            model_name='member',
            name='emergency_contact',
        ),
        migrations.RemoveField(
            model_name='member',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='member',
            name='status',
        ),
        migrations.RemoveField(
            model_name='member',
            name='whatsapp',
        ),
    ]
