# Generated by Django 6.0.7 on 2026-07-14 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_rename_plan_member_membership_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='fee_status',
            field=models.CharField(default='Paid', max_length=10),
        ),
        migrations.AddField(
            model_name='member',
            name='next_due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
