# Generated by Django 6.0.7 on 2026-07-12 16:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='date',
            new_name='attendance_date',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='method',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='time',
        ),
        migrations.AddField(
            model_name='attendance',
            name='entry_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='exit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Inside', 'Inside'), ('Exited', 'Exited'), ('Auto Exit', 'Auto Exit')], default='Inside', max_length=20),
        ),
    ]
